name: PlatformIO Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --user platformio

    - name: Build using PlatformIO
      run: |
        platformio run

    - name: Upload firmware_merged.bin
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: .pio/build/lolin_s2_mini/firmware_merged.bin
